version: 2
updates:
- package-ecosystem: npm
  directory: report
  schedule:
    interval: weekly
  versioning-strategy: increase-if-necessary
- package-ecosystem: npm
  directory: docs
  schedule:
    interval: weekly
  versioning-strategy: increase-if-necessary
- package-ecosystem: pip
  directory: docs
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
