#!/bin/sh -e
DEPLOY="$( cd "$(dirname "$( dirname "${BASH_SOURCE[0]}" )" )" >/dev/null && pwd )"
VERSION="$1"
TOKEN="$2"

if [ -z "$VERSION" ]
then
    echo "You need to specify a version (ex. 1.0.0)"
    exit 1
fi

if [ -z "$TOKEN" ]
then
    echo "You need to specify a download token. Contact us if you don't have one."
    exit 1
fi

VERSIONS_DIR="$DEPLOY/versions"
echo "Downloading assets for version $VERSION into $VERSIONS_DIR"
ZIP="$VERSIONS_DIR/download.zip"
rm -f $ZIP
curl -fL "https://us-central1-pullapprove.cloudfunctions.net/pullapprove-downloader?version=$VERSION&token=$TOKEN" -o $ZIP
unzip $ZIP -d $VERSIONS_DIR
